coverage:
  status:
    project: # https://docs.codecov.com/docs/commit-status
      default:
        target: 65%
        threshold: 5%
ignore:
  - ".gitignore"
  - ".flake8"
  - "uv.lock"
  - "**/*.yaml"
  - "**/*.yml"
  - "**/*.toml"
  - "**/*.md"
  - "**/*.sh"
  - "**/*.ini"
  - "research"
  - "**/Makefile"
github_checks:
    annotations: false
