import os

NUM_CLIENTS = int(os.getenv("NUM_CLIENTS"))
NUM_ROUNDS = int(os.getenv("NUM_ROUNDS"))
SERVER_INTERNAL_HOST = os.getenv("SERVER_INTERNAL_HOST")
SERVER_INTERNAL_PORT = os.getenv("SERVER_INTERNAL_PORT")