# Parameters that describe server
n_server_rounds: 6 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 4 # The number of clients in the FL experiment
local_epochs: 3 # The number of epochs to complete for client
batch_size: 32 # The batch size for client training
sparsity_level: 0.1 # Level of sparsity which indicates how many parameters are exchanged

# checkpointing
checkpoint_path: "examples/sparse_tensor_partial_exchange_example"
