# Parameters that describe server
n_server_rounds: 15 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 6 # The number of clients in the FL experiment
local_epochs: 1 # The number of epochs to complete for client (NOT USED FOR FLAMBY)
batch_size: 64 # The batch size for client training (NOT USED FOR FLAMBY)
local_steps: 100 # The number of local training steps to perform.
warmup_rounds: 5 # The number of rounds to run FedAvg before starting Scaffold
