# YAML parser's must-have configs
n_server_rounds: 500

# must have at least 3 clients
n_clients: 500    # set this parameter in run.sh as well
n_clients_per_node: 15 # match this parameter with the client slurm script 
privacy_amplification_sampling_ratio: 0.1
batch_size: 30
momentum: 0.9

dataset: "femnist"


# Other configs
# local_epochs: None
local_steps: 40
global_lr: 1
checkpoint_path: "examples/ddgm_examples"

# privacy parameters
enable_dp: false
clipping_bound: 3
noise_multiplier: 1
bias: 0.06
sign_vector_seed: 42
model_integer_range_exponent: 16   # modulus = 2^model_integer_range_exponent

# mode: diff_params or params TODO: add gradient
clipping_object: "diff_params"
