# YAML parser's must-have configs
n_server_rounds: 1500

# must have at least 3 clients
n_clients: 300    # set this parameter in run.sh as well
privacy_amplification_sampling_ratio: 1
batch_size: 20

dataset: "femnist"

# # optional parameter
# model_integer_range: 9999

# Other configs
# local_epochs: None
local_steps: 1
checkpoint_path: "examples/ddgm_examples"

# privacy parameters
enable_dp: true
clipping_bound: 0.03
granularity: 0.0015
noise_multiplier: 1.2
bias: 0.06
# private_vector_dimension: 1018174

sign_vector_seed: 1

# not used by client directly
model_integer_range_exponent: 16   # modulus = 2^model_integer_range_exponent