# Parameters that describe server
n_server_rounds: 20 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 3 # The number of clients in the FL experiment
local_epochs: 1 # The number of epochs to complete for client (NOT USED FOR FLAMBY)
batch_size: 64 # The batch size for client training (NOT USED FOR FLAMBY)
local_steps: 100 # The number of local training steps to perform.

# privacy settings (defaults to continuous Gaussian noise)
gaussian_noise_variance: 10
