# Parameters that describe server
n_server_rounds: 5 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 2 # The number of clients in the FL experiment
local_epochs: 5 # The number of epochs to complete for client
batch_size: 64 # The batch size for client training

source_specified: False # Specifies whether the server knows the source
# of truth for performing feature alignment a priori. If it is False,
# then the server will randomly poll a client to obtain this information.
