
version: '3'
services: # Define services in multi-container Docker Application
    fl_server: # FL Server container specification
        build:
            context: ../../
            dockerfile: examples/docker_basic_example/fl_server/Dockerfile

        container_name: fl_server # Name of the container
        ports: # Mapping of local ports to virtual docker ports
        - "5001:8080"

    fl_client_1:  # FL Client container specification
        build:
            context: ../../
            dockerfile: examples/docker_basic_example/fl_client/Dockerfile

        container_name: fl_client_1 # Name of the container
        depends_on: # Container dependencies
        - fl_server
        environment:  # Specification of environment variables
            FLOWER_CLIENT_NUMBER: "1"

    fl_client_2: # FL Client container specification
        build:
            context: ../../
            dockerfile: examples/docker_basic_example/fl_client/Dockerfile

        container_name: fl_client_2 # Name of the container
        depends_on: # Container dependencies
        - fl_server
        environment: # Specification of environment variables
            FLOWER_CLIENT_NUMBER: "2"
