# Parameters that describe server
n_server_rounds: 2 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 2 # The number of clients in the FL experiment
local_steps: 5 # The number of epochs to complete for client
batch_size: 128 # The batch size for client training
evaluate_after_fit: True # Also collects the results of evaluation with the local model with the validation set
