# Server settings
n_server_rounds: 10
n_clients: 3

# Client learning settings
client_sampling_rate: 0.66
local_epochs: 1
batch_size: 64

# Differential privacy parameters
noise_multiplier: 1.0
clipping_bound: 5.0
