# YAML parser's must-have configs
n_server_rounds: 4

# must have at least 3 clients
n_clients: 3    # set this parameter in run.sh as well
batch_size: 16
shamir_reconstruction_threshold: 2

# # optional parameter
# model_integer_range: 9999

# Other configs
local_epochs: 1
checkpoint_path: "examples/secure_aggregation_example"

# privacy parameters
clipping_threshold: 100
granularity: 0.000001
noise_scale: 0.00001
bias: 0.607

# not used by client directly
model_integer_range_exponent: 16   # modulus = 2^model_integer_range_exponent