# YAML parser's must-have configs
n_server_rounds: 4

# must have at least 3 clients
n_clients: 3
batch_size: 16

# Other configs
local_epochs: 1
checkpoint_path: "examples/secure_aggregation_example"
