dataset_json: /home/shawn/Code/nnunet_storage/nnUNet_raw/Dataset012_PICAI-debug/dataset.json
plans: /home/shawn/Code/nnunet_storage/nnUNet_preprocessed/Dataset011_PICAI/nnUNetPlans.json
2d:
  # Pass nnunet results folder
  - /home/shawn/Code/nnunet_storage/nnUNet_results/Dataset012_PICAI-debug/nnUNetTrainer_1epoch__nnUNetPlans__2d
  # Pass individual checkpoint
  - /home/shawn/Code/nnunet_storage/nnUNet_results/Dataset012_PICAI-debug/nnUNetTrainer_1epoch__nnUNetPlans__2d/fold_0/checkpoint_final.pth
3d_fullres:
  - /home/shawn/Code/nnunet_storage/nnUNet_results/Dataset012_PICAI-debug/nnUNetTrainer_1epoch__nnUNetPlans__3d_fullres/fold_0/checkpoint_final.pth
