dataset_json: /projects/aieng/public/PICAI/nnUNet/nnUNet_raw/Dataset005_Haider_710/dataset.json
plans: /projects/aieng/public/PICAI/nnUNet/nnUNet_preprocessed/Dataset005_Haider_710/nnUNetPlans.json
2d:
  # Pass individual checkpoint
  - /projects/aieng/public/PICAI/nnUNet/nnUNet_preprocessed/Dataset005_Haider_710/model.pt
